# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file
    - run: mkdir solanaj
      name: Create SolanaJ directory
    - run: cd solanaj
      name: Navigate to SolanaJ directory
    - uses: actions/checkout@v2
      with:
        repository: skynetcapital/solanaj
        ref: v1.3
    - name: Build SolanaJ with Maven
      run: mvn clean install
    - run: cd ../
      name: Navigate to root maven directory
    - uses: actions/checkout@v2
    - name: Package SolanaJ-Programs with Maven
      run: mvn -B package --file pom.xml
    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy
      env:
        GITHUB_TOKEN: ${{ github.token }}

